apiVersion: v1
kind: Secret
metadata:
  name: mysql8-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql8.secret.root_pw | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysql8.secret.user_pw | b64enc }}