---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  serviceName: adminer
  replicas: {{ .Values.adminer.deploy.replicas | default "4" }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:latest
          ports:
            - containerPort: {{ .Values.phpmyadmin.deploy.port | default "8080" }}
          env:
            - name: ADMINER_DESIGN
              value: "pappu687"
            - name: ADMINER_DEFAULT_SERVER
              value: "mysql8.default.svc.cluster.local"
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.phpmyadmin.deploy.port | default "8080" }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.phpmyadmin.deploy.port | default "8080" }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  type: NodePort
  selector:
    app: adminer
  ports:
    - port: {{ .Values.phpmyadmin.deploy.servicePort | default "8888" }}
      targetPort: {{ .Values.phpmyadmin.deploy.port | default "8080" }}
