##########################
# Parametros particulares 
##########################

mysql8:
  configMap:
    database: phpmyadmin
    user: phpmyadmin
  secret:
    root_pw: root.password
    user_pw: phpmyadmin
  pv:
    capacity: 1Gi
    accessMode: ReadWriteOnce
    path: /tmp/mysql_pre2

phpmyadmin:
  deploy:
    replicas: 4
    port:
    servicePort:
adminer:
  deploy:
    replicas: 4
    port:
    servicePort: